const menu=document.getElementById('menu');
const resultsScreen=document.getElementById('results-screen');
const pauseScreen=document.getElementById('pause-screen');
const fileInput=document.getElementById('audioFile');
const startBtn=document.getElementById('startBtn');
const menuBtn=document.getElementById('menuBtn');
const resumeBtn=document.getElementById('resumeBtn');
const quitBtn=document.getElementById('quitBtn');
const gameContainer=document.getElementById('game-container');
const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const songMetadataBox=document.getElementById('song-metadata');
const playlistListEl=document.getElementById('playlist-list');
const playlistDropdown=document.getElementById('playlist-dropdown');
const playlistToggle=document.getElementById('playlistToggle');
const playlistToggleText=document.getElementById('playlistToggleText');
const bgVideo=document.getElementById('bg-video');
const hudPauseBtn=document.getElementById('hudPauseBtn');
const hudFullscreenBtn=document.getElementById('hudFullscreenBtn');
const menuFullscreenBtn=document.getElementById('menuFullscreenBtn');
const hudLifeFill=document.getElementById('hudLifeFill');
const hudScore=document.getElementById('hudScore');
const hudCombo=document.getElementById('hudCombo');
const hudProgressFill=document.getElementById('hudProgressFill');
const hudTimeLeft=document.getElementById('hudTimeLeft');
const comboFlash=document.getElementById('combo-flash');
const particleCanvas=document.getElementById('particle-canvas');
const particleCtx=particleCanvas.getContext('2d');
const colorSchemeSelect=document.getElementById('colorSchemeSelect');
const colorPreview=document.getElementById('colorPreview');

bgVideo.pause();

let audioCtx=null,audioBuffer=null,audioOffsetMs=0,audioSource=null,songStartTime=0;
let isPlaying=false,isPaused=false,pauseStartTime=0,totalPausedTime=0;
let gamePhase='menu',phaseStartTime=0,lastHitEarly=false,lastCountdownSecond=-1;
let notes=[],noteStartIndex=0,score=0,combo=0,comboAnim=0,playerLife=100;
let feedbackText='',feedbackTimer=0,estimatedBPM=120;
let stats={perfect:0,good:0,miss:0,maxCombo:0};
let currentTrackMeta={artist:'Unknown',title:'Unknown Track'};
let playlistTracks=[],selectedPlaylistTrack=null;
let previewSource=null,previewGain=null;
let holdEffects=[],milestoneEffects=[],particles=[];
let LANE_COUNT=4,LANE_WIDTH=0,RECEPTOR_Y=0;
const BOTTOM_MARGIN_CSS=100;
let difficultySetting='medium',speedMultiplier=3,scrollSpeed=1200;
let pressedLanes=[false,false,false,false],touchLaneMap={};
let ARROW_COLORS=['#8D3CFF','#20E8FF','#FFD700','#FF4757'];
const COLOR_SCHEMES={cyber:['#8D3CFF','#20E8FF','#FFD700','#FF4757'],classic:['#00FFFF','#B026FF','#FF00FF','#00FFFF'],neon:['#00FF88','#20E8FF','#FF3ED8','#FF8C00']};
let flashTimeout=null,hudThrottleAcc=0,resizeTimer=null,gameLoopId=null;
let _laneGradCache={},_laneGradCacheH=0,_comboGrad=null;
const arrowCache={},judgmentCache={};
let audioStarted=false;

function formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return m+':'+(sec<10?'0':'')+sec}
function pseudoRandom(s){let x=Math.sin(s*12.9898)*43758.5453;return x-Math.floor(x)}
function getLaneGrad(l){if(_laneGradCacheH!==canvas.height){_laneGradCache={};_laneGradCacheH=canvas.height;_comboGrad=null}if(!_laneGradCache[l]){const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(1,ARROW_COLORS[l]);_laneGradCache[l]=g}return _laneGradCache[l]}
function playBeep(f,d,t){t=t||'sine';if(!audioCtx)return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(0.15,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
function estimateBPM(b){const d=b.getChannelData(0),sr=b.sampleRate,bs=Math.floor(sr*0.05),peaks=[];let me=0;for(let i=0;i<d.length;i+=bs){let s=0;for(let j=0;j<bs&&(i+j)<d.length;j++)s+=d[i+j]*d[i+j];const e=Math.sqrt(s/bs);if(e>me)me=e;peaks.push({energy:e})}const th=me*0.4,pt=[];for(let i=1;i<peaks.length-1;i++){if(peaks[i].energy>th&&peaks[i].energy>peaks[i-1].energy&&peaks[i].energy>peaks[i+1].energy)pt.push(i*0.05)}const iv=[];for(let i=1;i<pt.length;i++){const d=pt[i]-pt[i-1];if(d>0.3&&d<1.5)iv.push(d)}if(iv.length===0)return 120;iv.sort((a,b)=>a-b);const mi=iv[Math.floor(iv.length/2)];let bpm=Math.round(60/mi);while(bpm<80)bpm*=2;while(bpm>180)bpm=Math.round(bpm/2);return bpm}
function deriveMetaFromFilename(n){const c=n.replace(/\.[^/.]+$/,''),p=c.split('-');if(p.length>1)return{artist:p[0].trim(),title:p.slice(1).join('-').trim()};return{artist:'Unknown Artist',title:c}}
function applyMetaToUI(){document.getElementById('metaArtist').innerText=currentTrackMeta.artist;document.getElementById('metaTitle').innerText=currentTrackMeta.title;document.getElementById('metaDuration').innerText=formatTime(audioBuffer.duration);document.getElementById('metaBpm').innerText=estimatedBPM;document.getElementById('metaNotes').innerText=notes.length;songMetadataBox.style.display='grid'}
function updateColorPreview(s){const c=COLOR_SCHEMES[s];if(!c||!colorPreview)return;const sq=colorPreview.querySelectorAll('div');for(let i=0;i<sq.length&&i<c.length;i++)sq[i].style.background=c[i]}
async function loadPlaylistManifest(){try{const r=await fetch('music/playlist.json',{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d))return normalizePlaylist(d)}}catch(e){}try{const r=await fetch('music/',{cache:'no-store'});if(r.ok){const h=await r.text();const m=Array.from(h.matchAll(/href="([^"?#]+\.(?:mp3|wav|ogg|m4a))"/gi)).map(x=>decodeURIComponent(x[1]));if(m.length)return normalizePlaylist(m)}}catch(e){}return[]}
function normalizePlaylist(l){return l.map(i=>{if(typeof i==='string'){const f=i.includes('/')?i:'music/'+i;const m=deriveMetaFromFilename(i.split('/').pop());return{file:f,artist:m.artist,title:m.title}}if(i&&i.file){const f=i.file.includes('/')?i.file:'music/'+i.file;const fb=deriveMetaFromFilename(i.file.split('/').pop());return{file:f,artist:i.artist||fb.artist,title:i.title||fb.title}}return null}).filter(Boolean)}
function renderPlaylist(){if(!playlistListEl)return;if(playlistTracks.length===0){playlistListEl.innerHTML='<p class="playlist-empty">No tracks found. Drop mp3 files into the "music" folder and list them in music/playlist.json — or upload a track manually below.</p>';if(playlistToggleText)playlistToggleText.textContent='No tracks found';return}playlistListEl.innerHTML='';playlistTracks.forEach(t=>{const item=document.createElement('div');item.className='playlist-item';const info=document.createElement('div');info.className='pl-info';const titleEl=document.createElement('div');titleEl.className='pl-title';titleEl.textContent=t.title;const artistEl=document.createElement('div');artistEl.className='pl-artist';artistEl.textContent=t.artist;info.appendChild(titleEl);info.appendChild(artistEl);const badge=document.createElement('span');badge.className='pl-badge';badge.textContent='▶ PREVIEW';item.appendChild(info);item.appendChild(badge);item.addEventListener('click',()=>selectPlaylistTrack(t,item));playlistListEl.appendChild(item)})}
async function selectPlaylistTrack(t,item){if(gamePhase!=='menu')return;stopPreview();fileInput.value='';document.querySelectorAll('.playlist-item').forEach(el=>el.classList.remove('active'));item.classList.add('active');selectedPlaylistTrack=t;startBtn.innerText='PROCESSING AUDIO...';startBtn.disabled=true;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended'){try{await audioCtx.resume()}catch(e){}}const r=await fetch(t.file);if(!r.ok)throw new Error('fetch failed: '+r.status);const ab=await r.arrayBuffer();audioBuffer=await audioCtx.decodeAudioData(ab);currentTrackMeta.artist=t.artist;currentTrackMeta.title=t.title;estimatedBPM=estimateBPM(audioBuffer);notes=autoGenerateChart(audioBuffer,difficultySetting);applyMetaToUI();startBtn.innerText='INITIALIZE UPLINK';startBtn.disabled=false;if(playlistToggleText)playlistToggleText.textContent=t.artist+' - '+t.title;closePlaylistDropdown();startPreviewLoop()}catch(err){alert('Could not load "'+t.title+'". Make sure the file exists in the music folder and the site is served over http(s), not opened directly from disk.');startBtn.innerText='INITIALIZE UPLINK';startBtn.disabled=true;item.classList.remove('active');selectedPlaylistTrack=null}}
function openPlaylistDropdown(){if(playlistDropdown)playlistDropdown.classList.add('open')}
function closePlaylistDropdown(){if(playlistDropdown)playlistDropdown.classList.remove('open')}
function togglePlaylistDropdown(){if(!playlistDropdown)return;if(playlistDropdown.classList.contains('open'))closePlaylistDropdown();else openPlaylistDropdown()}
function startPreviewLoop(){stopPreview();if(!audioCtx||!audioBuffer)return;const pl=Math.min(5,audioBuffer.duration),off=Math.min(Math.max(0,audioBuffer.duration*0.15),Math.max(0,audioBuffer.duration-pl));try{previewSource=audioCtx.createBufferSource();previewSource.buffer=audioBuffer;previewSource.loop=false;previewGain=audioCtx.createGain();previewGain.gain.value=0.55;previewSource.connect(previewGain);previewGain.connect(audioCtx.destination);previewSource.start(0,off,pl);previewSource.onended=function(){previewSource=null;previewGain=null}}catch(e){previewSource=null;previewGain=null}}
function stopPreview(){if(previewSource){try{previewSource.stop()}catch(e){}previewSource=null}if(previewGain){try{previewGain.disconnect()}catch(e){}previewGain=null}}
function autoGenerateChart(b,d){const rd=b.getChannelData(0),sr=b.sampleRate,gen=[];let th=d==='easy'?0.32:(d==='medium'?0.20:0.12),sm=d==='easy'?10:(d==='medium'?6:3),hp=d==='easy'?0:(d==='medium'?0.12:0.22),dc=d==='easy'?0:(d==='medium'?0.08:0.18),ws=Math.floor(sr*0.04),ll=-1,ldt=-999,nah=0,ct=b.duration-5,bd=60/estimatedBPM,sd=bd/4;for(let i=0;i<rd.length;){let s=0;for(let j=0;j<ws&&(i+j)<rd.length;j++)s+=rd[i+j]*rd[i+j];const r=Math.sqrt(s/ws);if(r>th){let ht=i/sr;if(ht<nah){i+=ws;continue}if(ht>=ct)break;let st=Math.round(ht/sd)*sd;if(st<nah)st=Math.ceil(nah/sd)*sd;if(st>=ct)break;let l=Math.floor(pseudoRandom(st*99+i)*LANE_COUNT);if(l===ll)l=(l+1)%LANE_COUNT;ll=l;const ih=(d!=='easy')&&(pseudoRandom(st*33)<hp),hd=ih?Number((pseudoRandom(st*77)*0.8+0.4).toFixed(2)):0;gen.push({lane:l,targetHitTime:Number(st.toFixed(3)),isHold:ih,holdDuration:hd,hit:false,holding:false,missed:false,hitAnim:0});if(d!=='easy'&&!ih&&(st-ldt)>1.2&&pseudoRandom(st*55)<dc){ldt=st;const p=[];for(let l2=0;l2<LANE_COUNT;l2++){if(l2!==l)p.push(l2)}const sl=p[Math.floor(pseudoRandom(st*73)*p.length)];gen.push({lane:sl,targetHitTime:Number(st.toFixed(3)),isHold:false,holdDuration:0,hit:false,holding:false,missed:false,hitAnim:0})}if(ih)nah=st+hd+0.35;else nah=st+sd*0.5;i+=ws*sm}else{i+=ws}}return gen}
function initParticleCanvas(){particleCanvas.width=window.innerWidth;particleCanvas.height=window.innerHeight}
window.addEventListener('resize',initParticleCanvas);initParticleCanvas();
function spawnParticles(x,y,c,count){count=count||10;for(let i=0;i<count;i++){const a=Math.random()*2*Math.PI,s=80+Math.random()*120,sz=3+Math.random()*5;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-30,life:1,decay:0.02+Math.random()*0.03,size:sz,color:c||'hsl('+(Math.random()*360)+',80%,70%)'})}}
function updateParticles(d){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*d;p.y+=p.vy*d;p.vy+=120*d;p.life-=p.decay;if(p.life<=0)particles.splice(i,1)}}
function drawParticles(){particleCtx.clearRect(0,0,particleCanvas.width,particleCanvas.height);for(let i=0;i<particles.length;i++){const p=particles[i];particleCtx.globalAlpha=p.life*0.5;particleCtx.fillStyle=p.color;particleCtx.beginPath();particleCtx.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);particleCtx.fill()}particleCtx.globalAlpha=1}
function triggerComboFlash(){if(flashTimeout)return;comboFlash.classList.add('active');flashTimeout=setTimeout(function(){comboFlash.classList.remove('active');flashTimeout=null},80)}
function drawSolidArrow(ctx,x,y,w,h,lane,isReceptor,isHitFlash,isPressed){const state=isReceptor?(isPressed?'receptor_pressed':'receptor_idle'):(isHitFlash?'hit_flash':'note');const wk=Math.round(w),hk=Math.round(h),key=lane+'_'+state+'_'+wk+'_'+hk;if(!arrowCache[key]){const pad=48,cs=Math.max(wk,hk)+pad*2,off=document.createElement('canvas');off.width=cs;off.height=cs;const oc=off.getContext('2d');oc.translate(cs/2,cs/2);const rot=(lane===0?-Math.PI/2:(lane===1?Math.PI:(lane===2?0:Math.PI/2)));oc.rotate(rot);const sz=Math.min(w,h)*0.92,stem=sz*0.28,head=sz*0.42,headW=sz*0.58;oc.beginPath();oc.moveTo(0,-sz/2);oc.lineTo(headW,-sz/2+head);oc.lineTo(stem,-sz/2+head);oc.lineTo(stem,sz/2);oc.lineTo(-stem,sz/2);oc.lineTo(-stem,-sz/2+head);oc.lineTo(-headW,-sz/2+head);oc.closePath();const bc=ARROW_COLORS[lane]||'#888';if(isReceptor){if(isPressed){oc.fillStyle=bc;oc.shadowBlur=24;oc.shadowColor=bc;oc.fill();oc.shadowBlur=0;oc.lineWidth=3;oc.strokeStyle='#ffffff';oc.stroke()}else{oc.fillStyle='rgba(10,8,20,0.65)';oc.fill();oc.lineWidth=2;oc.strokeStyle='rgba(255,255,255,0.15)';oc.stroke();oc.shadowBlur=6;oc.shadowColor=bc;oc.lineWidth=1.5;oc.strokeStyle=bc;oc.globalAlpha=0.3;oc.stroke();oc.globalAlpha=1;oc.shadowBlur=0}}else{if(isHitFlash){oc.fillStyle='#ffffff';oc.shadowBlur=40;oc.shadowColor=bc;oc.fill();oc.shadowBlur=0;oc.lineWidth=3;oc.strokeStyle=bc;oc.stroke()}else{oc.fillStyle=bc;oc.shadowBlur=18;oc.shadowColor=bc;oc.fill();oc.shadowBlur=0;oc.lineWidth=1.5;oc.strokeStyle='rgba(255,255,255,0.3)';oc.stroke();oc.lineWidth=2.5;oc.strokeStyle='rgba(0,0,0,0.5)';oc.stroke()}}arrowCache[key]=off}const cached=arrowCache[key];const cx=(x+w/2)-(cached.width/2),cy=(y+h/2)-(cached.height/2);ctx.drawImage(cached,cx,cy)}
function resizeCanvas(){const dpr=Math.min(window.devicePixelRatio||1,1.5),rect=canvas.getBoundingClientRect(),cw=Math.max(1,rect.width),ch=Math.max(1,rect.height);canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);LANE_WIDTH=canvas.width/LANE_COUNT;RECEPTOR_Y=canvas.height-BOTTOM_MARGIN_CSS*dpr;for(const k in arrowCache)delete arrowCache[k];for(const k in judgmentCache)delete judgmentCache[k];_laneGradCache={};_laneGradCacheH=0;_comboGrad=null}
window.addEventListener('resize',function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(resizeCanvas,150)});
window.addEventListener('orientationchange',function(){setTimeout(resizeCanvas,200)});
function isFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement)}
function toggleFullscreen(){try{if(!isFullscreen()){const el=document.documentElement;if(el.requestFullscreen)el.requestFullscreen().catch(function(){});else if(el.webkitRequestFullscreen)el.webkitRequestFullscreen()}else{if(document.exitFullscreen)document.exitFullscreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen()}}catch(e){}}
function syncFullscreenIcons(){const lbl=isFullscreen()?'⤢':'⛶';if(hudFullscreenBtn)hudFullscreenBtn.innerText=lbl;if(menuFullscreenBtn)menuFullscreenBtn.innerText=isFullscreen()?'⤢ EXIT FULLSCREEN':'⛶ ENTER FULLSCREEN'}
document.addEventListener('fullscreenchange',function(){syncFullscreenIcons();setTimeout(resizeCanvas,100)});
document.addEventListener('webkitfullscreenchange',function(){syncFullscreenIcons();setTimeout(resizeCanvas,100)});
const LANE_BORDER_TOLERANCE=0.24;
function lanesFromTouch(touch,rect,scaleX){const cx=(touch.clientX-rect.left)*scaleX,lane=Math.floor(cx/LANE_WIDTH);if(lane<0||lane>=LANE_COUNT)return[];const lanes=[lane],lx=cx-lane*LANE_WIDTH,tol=LANE_WIDTH*LANE_BORDER_TOLERANCE;if(lx<tol&&lane-1>=0)lanes.push(lane-1);if(lx>LANE_WIDTH-tol&&lane+1<LANE_COUNT)lanes.push(lane+1);return lanes}
function rebuildPressedLanes(){pressedLanes[0]=pressedLanes[1]=pressedLanes[2]=pressedLanes[3]=false;for(const id in touchLaneMap){touchLaneMap[id].forEach(l=>{if(l>=0&&l<LANE_COUNT)pressedLanes[l]=true})}}
function laneStillTouched(lane){for(const id in touchLaneMap){if(touchLaneMap[id].indexOf(lane)!==-1)return true}return false}
function releaseLaneHold(lane){notes.forEach(n=>{if(n.holding&&n.lane===lane){n.holding=false;n.missed=true;registerMiss('RELEASED')}})}
function setTouchLanes(id,lanes){const prev=touchLaneMap[id]||[];touchLaneMap[id]=lanes;rebuildPressedLanes();prev.forEach(l=>{if(lanes.indexOf(l)===-1&&!laneStillTouched(l))releaseLaneHold(l)})}
function processLaneAction(lane){const cst=audioCtx.currentTime-songStartTime-totalPausedTime;if(cst<0)return;let tn=null;for(let i=noteStartIndex;i<notes.length;i++){const n=notes[i];if(!n.hit&&!n.missed&&n.lane===lane){tn=n;break}}if(!tn)return;const td=Math.abs(tn.targetHitTime-cst);if(td<=0.090){if(tn.isHold){tn.hit=true;tn.holding=true}else{registerHit(tn,'PERFECT!',300,'perfect',false)}}else if(td<=0.160){if(tn.isHold){tn.hit=true;tn.holding=true}else{const ie=cst<tn.targetHitTime;registerHit(tn,'GOOD',150,'good',ie)}}else if(td<=0.230){registerMiss('SYSTEM MISS')}}
function registerHit(note,grade,points,type,early){note.hit=true;note.hitAnim=12;score+=points;combo++;comboAnim=15;if(combo>stats.maxCombo)stats.maxCombo=combo;playerLife=Math.min(100,playerLife+6);if(type==='perfect')stats.perfect++;else stats.good++;feedbackText=grade;feedbackTimer=35;lastHitEarly=early||false;updateLifeBar();hudScore.innerText=score;hudCombo.innerText=combo+'x';if(combo>0&&combo%100===0){triggerComboFlash();const cx=window.innerWidth/2,cy=window.innerHeight/2;spawnParticles(cx,cy,null,15);milestoneEffects.push({text:combo+' COMBO!',progress:0,lifetime:60,scale:0.5})}}
function registerMiss(reason){combo=0;comboAnim=0;feedbackText=reason;feedbackTimer=35;stats.miss++;playerLife=Math.max(0,playerLife-8);lastHitEarly=false;updateLifeBar();hudCombo.innerText='0x';if(playerLife<=0)triggerFail()}
function updateLifeBar(){hudLifeFill.style.transform='scaleX('+(playerLife/100)+')';hudLifeFill.style.backgroundColor=playerLife>50?'#20E8FF':(playerLife>20?'#ffcc00':'#ff4757')}
function triggerFail(){isPlaying=false;if(audioSource){try{audioSource.stop()}catch(e){}}gameContainer.style.display='none';finishGame(true)}
function calculateRank(){if(notes.length===0)return'E';if(stats.perfect===notes.length&&stats.good===0&&stats.miss===0)return'S';const acc=(score/(notes.length*300))*100,cp=(stats.maxCombo/notes.length)*100,rating=(acc*0.75)+(cp*0.25);if(rating>=90)return'A';if(rating>=80)return'B';if(rating>=70)return'C';if(rating>=55)return'D';return'E'}
function finishGame(isFailed){isFailed=isFailed||false;isPlaying=false;gamePhase='results';if(audioSource){try{audioSource.stop()}catch(e){}}gameContainer.style.display='none';const rank=isFailed?'E':calculateRank();document.getElementById('resRank').innerText=rank;document.getElementById('resTitle').innerText=isFailed?'SYSTEM FAILURE':'AUDITION CLEARED';document.getElementById('resTitle').style.color=isFailed?'#ff4757':'#20E8FF';document.getElementById('resIcon').innerText=isFailed?'⚠️':'🏆';document.getElementById('resScore').innerText=score;document.getElementById('resMaxCombo').innerText=stats.maxCombo;document.getElementById('resPerfect').innerText=stats.perfect;document.getElementById('resGood').innerText=stats.good;document.getElementById('resMiss').innerText=stats.miss;resultsScreen.style.display='block';if(gameLoopId){cancelAnimationFrame(gameLoopId);gameLoopId=null}if(audioCtx&&audioCtx.state==='suspended'){audioCtx.resume()}}
function gameLoop(timestamp){if(gamePhase==='menu'||gamePhase==='results'){gameLoopId=null;return}if(isPaused){gameLoopId=requestAnimationFrame(gameLoop);return}try{const delta=0.016;updateParticles(delta);drawParticles();ctx.clearRect(0,0,canvas.width,canvas.height);const grad=ctx.createLinearGradient(0,0,0,canvas.height);grad.addColorStop(0,'rgb(5,5,10)');grad.addColorStop(1,'rgb(15,10,25)');ctx.fillStyle=grad;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(32,232,255,0.15)';ctx.setLineDash([10,15]);ctx.lineWidth=1.5;for(let i=1;i<LANE_COUNT;i++){const x=i*LANE_WIDTH;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}ctx.setLineDash([]);const elapsed=(timestamp-phaseStartTime)/1000;if(gamePhase==='countdown'){const tl=5.0-elapsed,cs=Math.ceil(tl);if(cs!==lastCountdownSecond&&cs>=1&&cs<=5){lastCountdownSecond=cs;playBeep(cs===1?880:440,0.12,'square')}drawUI();ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 '+Math.round(canvas.width*0.13)+'px "Orbitron",sans-serif';ctx.strokeStyle='#20E8FF';ctx.lineWidth=3;const num=Math.ceil(tl);ctx.strokeText(num>0?num:1,canvas.width/2,canvas.height/2);ctx.restore();if(tl<=0){gamePhase='buffer';phaseStartTime=performance.now();lastCountdownSecond=-1}}else if(gamePhase==='buffer'){const tl=2.0-elapsed;if(tl<=1.0&&lastCountdownSecond!=='go'){lastCountdownSecond='go';playBeep(990,0.15,'square')}drawUI();ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 '+Math.round(canvas.width*0.045)+'px "Orbitron",sans-serif';ctx.fillStyle=tl>1.0?'#FF3ED8':'#20E8FF';ctx.fillText(tl>1.0?'SYSTEM LOADING':'LINKED',canvas.width/2,canvas.height/2);ctx.restore();if(tl<=0){gamePhase='playing';isPlaying=true;audioStarted=true;const prd=RECEPTOR_Y/scrollSpeed,off=audioOffsetMs/1000;songStartTime=audioCtx.currentTime+prd-off;audioSource=audioCtx.createBufferSource();audioSource.buffer=audioBuffer;audioSource.playbackRate.value=1.0;audioSource.connect(audioCtx.destination);audioSource.start(audioCtx.currentTime+prd);audioSource.onended=function(){if(isPlaying&&!isPaused)finishGame(false)}}}else if(gamePhase==='playing'){const cst=audioCtx.currentTime-songStartTime-totalPausedTime;hudThrottleAcc+=1;if(audioBuffer&&hudThrottleAcc>=6){hudThrottleAcc=0;const prog=Math.max(0,Math.min(1,cst/audioBuffer.duration));hudProgressFill.style.transform='scaleX('+prog+')';hudTimeLeft.innerText=formatTime(Math.max(0,audioBuffer.duration-cst))}drawUI();updateAndDrawNotes(cst);drawJudgment();drawCombo();drawHoldEffects();drawMilestoneEffects()}}catch(err){finishGame(true);return}if(gamePhase!=='results'){gameLoopId=requestAnimationFrame(gameLoop)}else{gameLoopId=null}}
function drawUI(){for(let i=0;i<LANE_COUNT;i++){const x=i*LANE_WIDTH,w=LANE_WIDTH,isPressed=pressedLanes[i]&&gamePhase==='playing';if(isPressed){ctx.save();ctx.globalAlpha=0.2;ctx.fillStyle=getLaneGrad(i);ctx.fillRect(x,0,w,canvas.height);ctx.restore()}drawSolidArrow(ctx,x+6,RECEPTOR_Y-32,w-12,64,i,true,false,isPressed)}}
function updateAndDrawNotes(cst){const mw=0.230;while(noteStartIndex<notes.length){const n=notes[noteStartIndex];const resolved=n.missed||(n.hit&&!n.holding&&n.hitAnim<=0);if(resolved)noteStartIndex++;else break}for(let i=noteStartIndex;i<notes.length;i++){const note=notes[i];if(note.missed)continue;if(note.holding){const het=note.targetHitTime+note.holdDuration;if(cst>=het){note.holding=false;note.hit=true;score+=200;combo++;comboAnim=15;if(combo>stats.maxCombo)stats.maxCombo=combo;stats.perfect++;playerLife=Math.min(100,playerLife+6);feedbackText='SYNCED!';feedbackTimer=25;updateLifeBar();hudScore.innerText=score;hudCombo.innerText=combo+'x';if(combo>0&&combo%100===0){triggerComboFlash();const cx=window.innerWidth/2,cy=window.innerHeight/2;spawnParticles(cx,cy,null,15);milestoneEffects.push({text:combo+' COMBO!',progress:0,lifetime:60,scale:0.5})}holdEffects.push({lane:note.lane,x:note.lane*LANE_WIDTH+LANE_WIDTH/2,y:RECEPTOR_Y,progress:0,lifetime:40,color:ARROW_COLORS[note.lane]});const rect=canvas.getBoundingClientRect(),sx=rect.width/canvas.width,sy=rect.height/canvas.height;const screenX=rect.left+(note.lane*LANE_WIDTH+LANE_WIDTH/2)*sx,screenY=rect.top+RECEPTOR_Y*sy;spawnParticles(screenX,screenY,ARROW_COLORS[note.lane],10);continue}const xp=(note.lane*LANE_WIDTH)+6,w=LANE_WIDTH-12,rem=(het-cst)*scrollSpeed;ctx.save();ctx.fillStyle=ARROW_COLORS[note.lane];ctx.globalAlpha=0.6;ctx.fillRect(xp+w/4,RECEPTOR_Y-rem,w/2,rem);ctx.restore();continue}if(note.hit){if(note.hitAnim>0){drawSolidArrow(ctx,(note.lane*LANE_WIDTH)+6,RECEPTOR_Y-32,LANE_WIDTH-12,64,note.lane,false,true,false);note.hitAnim--}continue}const tuh=note.targetHitTime-cst;if(cst>note.targetHitTime+mw){note.missed=true;registerMiss('SYSTEM MISS');continue}const ny=RECEPTOR_Y-(tuh*scrollSpeed);if(ny<-100)break;if(ny<=canvas.height+60){if(note.isHold){const xp=(note.lane*LANE_WIDTH)+6,w=LANE_WIDTH-12,tpl=note.holdDuration*scrollSpeed,ts=ny-tpl,te=ny,th=te-ts;if(th>0){ctx.save();ctx.fillStyle=ARROW_COLORS[note.lane];ctx.globalAlpha=0.5;ctx.fillRect(xp+w/4,ts,w/2,th);ctx.restore()}}drawSolidArrow(ctx,(note.lane*LANE_WIDTH)+6,ny-32,LANE_WIDTH-12,64,note.lane,false,false,false)}}}
function drawHoldEffects(){for(let i=holdEffects.length-1;i>=0;i--){const ef=holdEffects[i];ef.progress+=1/ef.lifetime;const alpha=1-ef.progress,radius=20+ef.progress*30;ctx.save();ctx.globalAlpha=alpha*0.4;ctx.strokeStyle=ef.color;ctx.lineWidth=3*(1-ef.progress*0.5);ctx.beginPath();ctx.arc(ef.x,ef.y,radius,0,Math.PI*2);ctx.stroke();ctx.restore();if(ef.progress>=1)holdEffects.splice(i,1)}}
function drawMilestoneEffects(){for(let i=milestoneEffects.length-1;i>=0;i--){const ef=milestoneEffects[i];ef.progress+=1/ef.lifetime;const alpha=1-ef.progress,scale=0.5+ef.progress*1.5;ctx.save();ctx.globalAlpha=alpha*0.8;ctx.textAlign='center';ctx.textBaseline='middle';const fs=40*scale;ctx.font='900 '+fs+'px "Orbitron",sans-serif';const grad=ctx.createLinearGradient(0,canvas.height/2-100,0,canvas.height/2+100);grad.addColorStop(0,'#ffffff');grad.addColorStop(1,'#20E8FF');ctx.fillStyle=grad;ctx.fillText(ef.text,canvas.width/2,canvas.height/2-20);ctx.restore();if(ef.progress>=1)milestoneEffects.splice(i,1)}}
function drawJudgment(){if(feedbackTimer>0){const color=feedbackText==='PERFECT!'?'#20E8FF':(feedbackText==='GOOD'?(lastHitEarly?'#FFD700':'#FF4757'):(feedbackText==='SYNCED!'?'#FF3ED8':'#ff4757'));const key=feedbackText+color;if(!judgmentCache[key]){const fs=Math.round(canvas.width*0.09),pad=40,off=document.createElement('canvas');off.width=Math.ceil(fs*feedbackText.length*0.7+pad*2);off.height=fs*2+pad*2;const oc=off.getContext('2d');oc.textAlign='center';oc.textBaseline='middle';oc.font='900 '+fs+'px "Orbitron",sans-serif';oc.shadowBlur=0;oc.fillStyle=color;oc.fillText(feedbackText,off.width/2,off.height/2);judgmentCache[key]=off}const off=judgmentCache[key],scale=1+(feedbackTimer/35)*0.2,cx=canvas.width/2,cy=canvas.height*0.42;ctx.save();ctx.globalAlpha=Math.min(1,feedbackTimer/8);ctx.drawImage(off,cx-(off.width*scale)/2,cy-(off.height*scale)/2,off.width*scale,off.height*scale);ctx.restore();feedbackTimer--}}
function drawCombo(){if(combo>=10){ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';if(comboAnim>0)comboAnim--;ctx.translate(canvas.width/2,canvas.height*0.28);ctx.scale(1+(comboAnim/15)*0.25,1+(comboAnim/15)*0.25);ctx.font='900 '+Math.round(canvas.width*0.2)+'px "Orbitron",sans-serif';if(!_comboGrad){_comboGrad=ctx.createLinearGradient(0,-50,0,20);_comboGrad.addColorStop(0,'#ffffff');_comboGrad.addColorStop(1,'#20E8FF')}ctx.fillStyle=_comboGrad;ctx.fillText(combo,0,0);ctx.font='700 '+Math.round(canvas.width*0.04)+'px "Rajdhani",sans-serif';ctx.fillStyle='#FF3ED8';ctx.fillText('CHAIN LINK',0,canvas.width*0.1);ctx.restore()}}
if(colorSchemeSelect){colorSchemeSelect.addEventListener('change',function(e){const s=e.target.value;ARROW_COLORS=COLOR_SCHEMES[s]||COLOR_SCHEMES.cyber;updateColorPreview(s);for(const k in arrowCache)delete arrowCache[k];for(const k in judgmentCache)delete judgmentCache[k]});updateColorPreview(colorSchemeSelect.value)}
document.querySelectorAll('#difficulty-container .selector-btn').forEach(function(b){b.addEventListener('click',function(){if(gamePhase!=='menu')return;document.querySelectorAll('#difficulty-container .selector-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');difficultySetting=b.getAttribute('data-diff');document.getElementById('metaDiff').innerText=difficultySetting==='easy'?'Crew':(difficultySetting==='medium'?'Manager':'Boss');if(audioBuffer){notes=autoGenerateChart(audioBuffer,difficultySetting);document.getElementById('metaNotes').innerText=notes.length}})});
document.querySelectorAll('#speed-container .selector-btn').forEach(function(b){b.addEventListener('click',function(){if(gamePhase!=='menu')return;document.querySelectorAll('#speed-container .selector-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');speedMultiplier=parseInt(b.getAttribute('data-speed'));scrollSpeed=speedMultiplier*400})});
fileInput.addEventListener('change',function(e){const f=e.target.files[0];if(!f)return;stopPreview();selectedPlaylistTrack=null;document.querySelectorAll('.playlist-item').forEach(el=>el.classList.remove('active'));if(playlistToggleText)playlistToggleText.textContent='Select a track…';startBtn.innerText='PROCESSING AUDIO...';startBtn.disabled=true;(async function(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const ab=await f.arrayBuffer();audioBuffer=await Promise.race([audioCtx.decodeAudioData(ab),new Promise(function(_,reject){setTimeout(function(){reject(new Error('Timeout'))},10000)})]);const meta=deriveMetaFromFilename(f.name);currentTrackMeta.artist=meta.artist;currentTrackMeta.title=meta.title;estimatedBPM=estimateBPM(audioBuffer);notes=autoGenerateChart(audioBuffer,difficultySetting);applyMetaToUI();if(playlistToggleText)playlistToggleText.textContent=currentTrackMeta.artist+' - '+currentTrackMeta.title+' (Manual)';startBtn.innerText='INITIALIZE UPLINK';startBtn.disabled=false}catch(err){alert('Could not process this audio file. Please try another standard MP3 or WAV.');startBtn.innerText='INITIALIZE UPLINK';startBtn.disabled=true;fileInput.value=''}})()});
if(playlistToggle){playlistToggle.addEventListener('click',function(e){e.stopPropagation();togglePlaylistDropdown()})}
document.addEventListener('click',function(e){if(playlistDropdown&&playlistDropdown.classList.contains('open')&&!playlistDropdown.contains(e.target)){closePlaylistDropdown()}});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closePlaylistDropdown()});
loadPlaylistManifest().then(function(t){playlistTracks=t;renderPlaylist()});
startBtn.addEventListener('click',function(){stopPreview();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();menu.style.display='none';resultsScreen.style.display='none';pauseScreen.style.display='none';gameContainer.style.display='flex';resizeCanvas();score=0;combo=0;comboAnim=0;playerLife=100;totalPausedTime=0;noteStartIndex=0;touchLaneMap={};pressedLanes=[false,false,false,false];stats={perfect:0,good:0,miss:0,maxCombo:0};holdEffects=[];milestoneEffects=[];particles=[];audioStarted=false;notes.forEach(function(n){n.hit=false;n.holding=false;n.missed=false;n.hitAnim=0});hudScore.innerText='0';hudCombo.innerText='0x';updateLifeBar();hudProgressFill.style.transform='scaleX(0)';hudTimeLeft.innerText=formatTime(audioBuffer.duration);gamePhase='countdown';phaseStartTime=performance.now();lastCountdownSecond=-1;if(gameLoopId){cancelAnimationFrame(gameLoopId);gameLoopId=null}gameLoopId=requestAnimationFrame(gameLoop)});
async function togglePause(){if(gamePhase!=='playing'||!audioCtx||!audioBuffer)return;if(!isPaused){isPaused=true;pauseStartTime=performance.now();touchLaneMap={};pressedLanes=[false,false,false,false];if(audioCtx.state==='running'){try{await audioCtx.suspend()}catch(e){}}pauseScreen.style.display='block'}else{pauseScreen.style.display='none';const pauseDuration=performance.now()-pauseStartTime;totalPausedTime+=pauseDuration/1000;if(audioCtx.state==='suspended'){try{await audioCtx.resume()}catch(e){}}isPaused=false;if(!gameLoopId){gameLoopId=requestAnimationFrame(gameLoop)}}}
function returnToMenu(){resultsScreen.style.display='none';pauseScreen.style.display='none';gameContainer.style.display='none';menu.style.display='block';if(audioSource){try{audioSource.stop()}catch(e){}audioSource=null}if(audioCtx&&audioCtx.state==='running'){audioCtx.suspend()}isPlaying=false;isPaused=false;gamePhase='menu';audioStarted=false;if(gameLoopId){cancelAnimationFrame(gameLoopId);gameLoopId=null}}
menuBtn.addEventListener('click',returnToMenu);quitBtn.addEventListener('click',returnToMenu);resumeBtn.addEventListener('click',togglePause);hudPauseBtn.addEventListener('click',togglePause);
if(hudFullscreenBtn)hudFullscreenBtn.addEventListener('click',toggleFullscreen);if(menuFullscreenBtn)menuFullscreenBtn.addEventListener('click',toggleFullscreen);syncFullscreenIcons();
canvas.addEventListener('touchstart',function(e){e.preventDefault();if(isPaused||!isPlaying||gamePhase!=='playing')return;const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width;for(let i=0;i<e.changedTouches.length;i++){const t=e.changedTouches[i],lanes=lanesFromTouch(t,rect,sx);if(lanes.length===0)continue;setTouchLanes(t.identifier,lanes);lanes.forEach(function(l){processLaneAction(l)})}},{passive:false});
canvas.addEventListener('touchmove',function(e){e.preventDefault();if(isPaused||!isPlaying||gamePhase!=='playing')return;const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width;for(let i=0;i<e.changedTouches.length;i++){const t=e.changedTouches[i],id=t.identifier,lanes=lanesFromTouch(t,rect,sx);if(lanes.length===0)continue;const primary=lanes[0],prevLanes=touchLaneMap[id];if(!prevLanes){setTouchLanes(id,lanes);lanes.forEach(function(l){processLaneAction(l)});continue}const prevPrimary=prevLanes[0];if(primary===prevPrimary){lanes.forEach(function(l){if(prevLanes.indexOf(l)===-1)processLaneAction(l)});setTouchLanes(id,lanes);continue}const step=primary>prevPrimary?1:-1;for(let lane=prevPrimary+step;;lane+=step){processLaneAction(lane);if(lane===primary)break}setTouchLanes(id,lanes)}},{passive:false});
canvas.addEventListener('touchend',function(e){e.preventDefault();for(let i=0;i<e.changedTouches.length;i++){const id=e.changedTouches[i].identifier,lanes=touchLaneMap[id]||[];delete touchLaneMap[id];rebuildPressedLanes();lanes.forEach(function(l){if(!laneStillTouched(l))releaseLaneHold(l)})}},{passive:false});
canvas.addEventListener('touchcancel',function(e){for(let i=0;i<e.changedTouches.length;i++){const id=e.changedTouches[i].identifier,lanes=touchLaneMap[id]||[];delete touchLaneMap[id];lanes.forEach(function(l){if(!laneStillTouched(l))releaseLaneHold(l)})}rebuildPressedLanes()},{passive:true});
document.addEventListener('keydown',function(e){if(isPaused||gamePhase!=='playing')return;const map={'a':0,'s':1,'k':2,'l':3};const key=e.key.toLowerCase();if(key in map&&!e.repeat){const lane=map[key];pressedLanes[lane]=true;processLaneAction(lane)}});
document.addEventListener('keyup',function(e){if(isPaused||gamePhase!=='playing')return;const map={'a':0,'s':1,'k':2,'l':3};const key=e.key.toLowerCase();if(key in map){const lane=map[key];pressedLanes[lane]=false;notes.forEach(n=>{if(n.holding&&n.lane===lane){n.holding=false;n.missed=true;registerMiss('RELEASED')}})}});
resizeCanvas();if(bgVideo){bgVideo.volume=0;bgVideo.play().catch(()=>{})}